conventions:
  - path: Faithlife/CodingGuidelines/conventions/editorconfig-root
  - path: Faithlife/CodingGuidelines/conventions/editorconfig-json
  - path: Faithlife/CodingGuidelines/conventions/editorconfig-md
  - path: Faithlife/CodingGuidelines/conventions/editorconfig-yaml
  - path: ../gitattributes
  - path: ../prettier-config
  - path: ../renovate
    settings:
      managers:
        - github-actions
        - custom.regex
      customManagers:
        - customType: regex
          managerFilePatterns:
            - /^repo-conventions-workflow\/convention\.ps1$/
          matchStrings:
            - "(?m)^\\$checkoutAction = '(?<depName>actions/checkout)@(?<currentValue>[^'\\s]+)'"
            - "(?m)^\\$setupDotnetAction = '(?<depName>actions/setup-dotnet)@(?<currentValue>[^'\\s]+)'"
          datasourceTemplate: github-tags
          versioningTemplate: regex:^v(?<major>\d+)$
  - path: ../github-settings
  - path: ../repo-conventions-workflow
  - path: ../license-mit
    settings:
      enabled: true
      copyright-holder: Adam Poit

pull-request:
  labels:
    - automation
