name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pester:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -RequiredVersion 6.0.0 -Scope CurrentUser -Force

      - name: Run tests
        shell: pwsh
        run: Invoke-Pester -Path . -CI
